openapi: 3.0.0
info:
  title: Order API
  version: 1.0.0
paths:
  /api/v1/order/{id}/status:
    get:
      operationId: getOrderStatusById
      summary: Get order status
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '404':
          description: Order not found
          content:
            application/json:
              examples:
                b002:
                  value:
                    message: "Order not found for id: b002"
        '200':
          description: Order found
          content:
            application/json:
              examples:
                a001:
                  value:
                    message: "Order status for a001: confirmed"
                default:
                  value:
                    message: "Default order status message"